export const ADD_FILTER = 'ADD_FILTER';
export const REMOVE_FILTER = 'REMOVE_FILTER';
export const APPLY_NUMERIC_FILTER = 'APPLY_NUMERIC_FILTER';
export const VERIFY_HAVE_FILTER = 'VERIFY_HAVE_FILTER';
export const FILTER_BY_NUMERIC_VALUES = 'FILTER_BY_NUMERIC_VALUES';
export const REMOVE_ALL_FILTERS = 'REMOVE_ALL_FILTERS';
export const APPLY_RESET_FILTERS = 'APPLY_RESET_FILTERS';
